# Generated by Django 3.0.8 on 2020-07-29 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=3, max_digits=6)),
                ('breadth', models.DecimalField(decimal_places=3, max_digits=6)),
                ('height', models.DecimalField(decimal_places=3, max_digits=6)),
                ('area', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=13)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
