# Generated by Django 3.0.8 on 2020-08-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='area',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='volume',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
    ]
