# Generated by Django 3.0.8 on 2020-08-02 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_inventory', '0003_auto_20200802_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='box',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13),
        ),
    ]
